name: Deploy to WordPress SVN

on:
  push:
    tags:
      - '*'  # Runs on any tag creation

jobs:
  deploy:
    name: Deploy Plugin to WordPress SVN
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: url-image-importer
